### ISSUE TITLE
Google colab

### ISSUE THREAD

**Issue by soujanyaporia** [saravananbcs/Tango-Demo-Colab#1]
Hi!

Thanks for setting up the colab! Would you mind to PR to https://github.com/declare-lab/tango? It would be great to have a colab demo. Many thanks!

--
Soujanya

**Comment by saravananbcs** [comment]
Hi Soujanya,

Awesome work with Tango. 

As requested I have raised a PR for the Basic google colab demo. I will work on finetuning the colab further to add steps to train the model and many more.

Below is the PR request. Please verify and accept it.

https://github.com/declare-lab/tango/pull/47

Thanks,
Saravanan

**Comment by saravananbcs** [comment]
Thanks for accepting the PR.
